# Path: mercury_duckling/configs/dataset.yaml
datasets:
  thermal:
    root: "../data/merged_dataset_delam_thm"
    ann_file: delamination.json
    type: thermal
  ape:
    root: "../data/merged_dataset_delam_ape"
    ann_file: delamination.json
    type: rgb
  driving:
    root: "../data/BigThermal/Frieburg_Thermal/ImagesRGB"
    ann_file: ../driving.json
    type: rgb
selected_data: driving
data: "${datasets[${selected_data}]}"

# General training data parameters
seed: 42
batch_size: 16
num_epochs: 105
val_interval: 4
num_workers: 4
split: 0.75   # train, val

# For testing the segmentation.
# split: 0
# val_interval: 1
# num_epochs: 1

# General transform parameters
target_size: [320, 960] # if target is not the same size as the images
crop_size: [266, 322] # if same "${target_size}"
colormap: Greys