# Path: mercury_duckling/configs/model.yaml
# BASE MODEL CONFIGURATION
models:
  SAM:
    type: interactive
    checkpoint: checkpoints/sam_vit_h_4b8939.pth
    size: vit_h
  RITM:
    type: interactive
    checkpoint: checkpoints/coco_lvis_h18_itermask.pth
    threshold: 0.49
  IUNET:
    type: interactive
    checkpoint: checkpoints/InterSegSynthFT.pth
  DINOV2:
    type: segmentor
    size: small
    out_indices: [8, 9, 10, 11]
    classes: 1
selected_model: DINOV2
model: "${models[${selected_model}]}"

# SAMPLER CONFIG & PARAMS FOR INTERACTIVE MODELS.
sampler:
  type: points    # points, boxes
  method: clicker # clicker, random
  args:
    click_limit: 20
    
# TRAINING PARAMS FOR SEGMENTOR MODELS
optimizer: 
  lr: 1e-5
loss: 
  mode: "binary"
  smooth: 1.0e-12 

# PRE AND POST PROCESSING FOR PIPELINES.
# TODO: implement pre and post processing methods and registry.
preprocessing:
  type: null
  args: null
postprocessing:
  type: null
  args: null
