# Path: mercury_duckling/configs/model.yaml
models:
  SAM:
    type: interactive
    checkpoint: checkpoints/sam_vit_h_4b8939.pth
    size: vit_h
  RITM:
    type: interactive
    checkpoint: checkpoints/coco_lvis_h18_itermask.pth
    threshold: 0.49
  IUNET:
    type: interactive
    checkpoint: checkpoints/InterSegSynthFT.pth
  DINOV2:
    type: segmentor
    size: small
    out_indices: [8, 9, 10, 11]
    classes: 1
    threshold: 0.5
selected_model: SAM
model: "${models[${selected_model}]}"
sampler:
  type: points    # points, boxes
  method: clicker # clicker, random
  args:
    click_limit: 20
preprocessing:
  type: null
  args: null
postprocessing:
  type: null
  args: null
optimizer: 
  lr: 1e-5
loss: 
  mode: "binary"
  smooth: 1.0e-12 
